### ISSUE TITLE
Want to become a contributor.

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaQuant/MarketTechnicals.jl#100]
Hello, I am interested in contributing to JuliaQuant. Can someone guide me on how to start?

**Comment by iblis17** [comment]
Hi @Vaibhavdixit02 !
Any form of contirubtion are wellcomed!

---
About contributions:

I think "contribution" contains several faces.

1. The most comment but important contribution is filing bugs and providing helpful info, like opening a issue on GitHub and showing us the reproducing steps. Breaking the program and letting everyone  know it is a nice contibution. It also encourages developers: "someone does use our code and he/she does care our project!".

2. You also can gripe and *provide a concrete suggestion*. Yes, please gripe and convince us that there is a better design/implementation. I know griping upsets everyone, but a rational suggestion is a origin of improvement as well!

3. discussion and design: a quite valuabe part of open source community. If you have any new idea, please tell us! This is source of inovation. Everyone in the community (including you and me) have different background and different perspective.

4. writting some code, solving issue and send it as PR. :)


---

Now, back to talk about JuliaQuant.
The big picture: https://github.com/JuliaQuant/Roadmap/issues/3
The roadmap: https://github.com/JuliaQuant/Roadmap

There are tons of repo need someone to polish up, upgrade syntax, upgrade documentation and take care of the design roadmap. If you are interested in some of project, and willing to take maintainership. Please discuss that with @milktrader. 

- Some discussion is here (but too long): https://github.com/JuliaQuant/MarketTechnicals.jl/issues/93

(Recently, I am struggle with julia 0.6 related issue in TimeSeries.jl...

**Comment by Vaibhavdixit02** [comment]
Thank you for such a detailed answer.

**Comment by milktrader** [comment]
@Vaidhavdixit02 take on an issue and solve it. Submit a Pull request. You are now a contributor. :smile:
