### ISSUE TITLE
Interested in better understanding and contributing.

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaQuant/MarketTechnicals.jl#101]
Hello, I am a student of Mathematics and Computing from India and I am quite interested in Quant, recently I read "Introduction to time series and forecasting" by Brockwell and Davis. I wanted to know about more resources to increase my knowledge and if there was some way to contribute to this project. Any reply would be greatly appreciated. Thanks.

**Comment by iblis17** [comment]
Hi @Vaibhavdixit02 ,
you may be insterested in #100 ;)

**Comment by iblis17** [comment]
Hi @Vaibhavdixit02 ,

There are some repo related to time series in JuliaStats

e.g. https://github.com/JuliaStats/TimeModels.jl

**Comment by Vaibhavdixit02** [comment]
@iblis17 Yes I remember that I had asked this before but I felt I needed some help. Anyway to chat with you if you are free sometime?

**Comment by iblis17** [comment]
@Vaibhavdixit02 feel free to join Julia's slack channel, chat or ping me; On #statistic channel, there are lots of people can help you.
(but I'm going to sleep now 💤

**Comment by iblis17** [comment]
FYI: https://discourse.julialang.org/t/announcing-a-julia-slack/4866

**Comment by Vaibhavdixit02** [comment]
Okay thanks! Will get in touch.
