### ISSUE TITLE
UndefVarError

### ISSUE THREAD

**Issue by samjurl** [JuliaQuant/MarketTechnicals.jl#107]
Hi there,

Have been testing MarketTechnicals today. Calling some functions such as "sma" or "ema" works fine. However for most others, such as "roc", I get the following error: "UndefVarError: roc not defined."

I am definitely using the package, and without using, I also get this error when calling sma or ema as expected.

I have Julia 0.6.2 installed and everything else is up to date with Pkg.update().

I am also using MarketData and TimeSeries and cannot carry out the examples when copied exactly. Have tried removing, re-adding, rebuilding MarketTechnicals etc. Seems it's somehow only half functional.

Any idea what could be going on?

**Comment by iblis17** [comment]
well, I do not release it yet. 
You can checkout the master branch via `Pkg.checkout("MarketTechnicals")`

**Comment by samjurl** [comment]
I see, sorry I hadn't understood that. I got around it however by defining the required functions based on the source code available in the documentation. It's very useful, many thanks!

**Comment by iblis17** [comment]
You can check the current release version in [GitHub](https://github.com/JuliaQuant/MarketTechnicals.jl/releases) and check your `Pkg.status("MarketTechnicals")`.

`roc` is a new feature that haven't been released yet, it's only available on master branch.
Please see [NEWS.md](https://github.com/JuliaQuant/MarketTechnicals.jl/blob/master/NEWS.md) .

**Comment by iblis17** [comment]
fine to close this issue now?

**Comment by samjurl** [comment]
Yeah the issue is cleared - cheers
