### ISSUE TITLE
rsi returns one extra value

### ISSUE THREAD

**Issue by stefabat** [JuliaQuant/MarketTechnicals.jl#108]
Hi,

I noticed that the `rsi` function returns arrays with one extra value.

E.g., if I have `N` periods, I get `N-1` period differences and if I use EMAs averaging over `n` periods of these arrays with `N-1` entries, I should get in the end `N-1 - n + 1` which is equal to `N-n`.

Nevertheless, using the function`rsi` I get `N-n+1` elements.

I looked into the code, and it seems that you add an extra zero at the beginning of the arrays `ups` and `dns`, why is that?

Cheers

**Comment by iblis17** [comment]
Hi, 
I just tried
```julia
julia> size(ema(cl, 14))                                                                                                                          
(487, 1)                                                                                                                                          
                                                                                                                                                  
julia> size(rsi(cl, 14))                                                                                                                          
(487, 1)
```
There isn't an extra value.

**Comment by stefabat** [comment]
That is the point, I argue that the `rsi` function should return in your example 486 elements.

**Comment by iblis17** [comment]
> I looked into the code, and it seems that you add an extra zero at the beginning of the arrays ups and dns, why is that?

ah, I got your point. I'm not sure the reason. 
will send a patch later.

**Comment by iblis17** [comment]
@stefabat Could you give this patch a try?

**Comment by stefabat** [comment]
Done.

It is working and it is correct (by comparing with both my own implementation and the one in `Indicators.jl`)

Cheers
