### ISSUE TITLE
Package Not Found

### ISSUE THREAD

**Issue by Sinansi** [JuliaQuant/MarketTechnicals.jl#121]
julia> using Pkg
julia> Pkg.add("MarketTechnicals")
ERROR: The following package names could not be resolved:
 * MarketTechnicals (not found in project, manifest or registry)
Please specify by known `name=uuid`.

**Comment by iblis17** [comment]
well, this package is not julia v1.0 + compatible,
related PR: https://github.com/JuliaQuant/MarketTechnicals.jl/pull/119

**Comment by Arkoniak** [comment]
This PR: https://github.com/JuliaQuant/MarketTechnicals.jl/pull/127 provided support for v1.1+
