### ISSUE TITLE
Moving Average Group By

### ISSUE THREAD

**Issue by ericvoots** [JuliaQuant/MarketTechnicals.jl#126]
with any of the moving averages, is it possible to do a group by function and return to the original dataframe?

i.e. if I have two tickers with different prices in the original dataframe that I feed into the moving average function?

**Comment by iblis17** [comment]
well, I'm not sure about your question.

I guess you have this 

time | ticker1 | ticker2
----- | ---- | ----
2020/1/1 | a | x
2020/1/2 | b | y
2020/1/3 | c | z

So, you can just get the MA via 
```
sma(ta[:ticker1])
sam(ta[:ticker2])
```
I think.

**Comment by ericvoots** [comment]
basically have a time series like this and would want to get what is in the MA column:

![image](https://user-images.githubusercontent.com/15186821/115808289-3b5a0f80-a3b8-11eb-96f6-eabfbfe14eef.png)

**Comment by iblis17** [comment]
ah, so you have a `DataFrame` as input, maybe you can just use the `groupby` function from `DataFrame`?

Maybe something like this
```julia
julia> df = DataFrame(
         date=[Date(2021,1,1):Day(1):Date(2021,1,6)...; Date(2021,1,1):Day(1):Date(2021,1,6)...],
         ticker=[fill("a", 6); fill("b", 6)],
         value=[vec(2:7); vec(5:10)]
       );
       
julia> combine(groupby(df, :ticker)) do subdf
        sma(subdf.value |> collect, 2)
       end
10×2 DataFrame
 Row │ ticker  x1      
     │ String  Float64 
─────┼─────────────────
   1 │ a           2.5
   2 │ a           3.5
   3 │ a           4.5
   4 │ a           5.5
   5 │ a           6.5
   6 │ b           5.5
   7 │ b           6.5
   8 │ b           7.5
   9 │ b           8.5
  10 │ b           9.5
```

**Comment by ericvoots** [comment]
Neat, okay that makes sense. 

N00b question how do i make the output from:

combine(groupby(df, :ticker)) do subdf
        sma(subdf.value |> collect, 2)
       end

become a new column on the original dataframe?

Thank you!

**Comment by iblis17** [comment]
I think you can do something like this,
since the `sma` don't support padding with `NaN` at this moment, you need to add it manually.
```julia
julia> combine(groupby(df, :ticker), :, :value => (subdf -> [NaN; sma(subdf |> collect, 2) |> vec]) => :ma_2 )
12×4 DataFrame
 Row │ ticker  date        value  ma_2    
     │ String  Date        Int64  Float64 
─────┼────────────────────────────────────
   1 │ a       2021-01-01      2    NaN
   2 │ a       2021-01-02      3      2.5
   3 │ a       2021-01-03      4      3.5
   4 │ a       2021-01-04      5      4.5
   5 │ a       2021-01-05      6      5.5
   6 │ a       2021-01-06      7      6.5
   7 │ b       2021-01-01      5    NaN
   8 │ b       2021-01-02      6      5.5
   9 │ b       2021-01-03      7      6.5
  10 │ b       2021-01-04      8      7.5
  11 │ b       2021-01-05      9      8.5
  12 │ b       2021-01-06     10      9.5
```

**Comment by ericvoots** [comment]
you rock, thank you
