### ISSUE TITLE
assumed ordering is wrong

### ISSUE THREAD

**Issue by LeoK987** [JuliaQuant/MarketTechnicals.jl#20]
The indexing order seems to assume that the oldest data is at index n and the newest at index 1. But that is not how typical data are arranged. Typically, the oldest data is at index 1 and the newest at index n

In the typical ordering of the data, should the for loop be as follows?

````julia
for i in n:length(ta)
vals[i] = mean(ta.values[i-(n-1):i])
end
````

**Comment by milktrader** [comment]
stale issue.
