### ISSUE TITLE
length of output should stay the same as the input

### ISSUE THREAD

**Issue by LeoK987** [JuliaQuant/MarketTechnicals.jl#21]
I see that the current output from functions like sma is of length N-n+1, where N is the original length of the timeseries. While that is reasonable, it is practically inconvenient. For further calculation between the output timeseries and the original timeseries, the end user may have to spend extra effort dealing with syncing and the omitted values.

I suggest that these functions keep the original length. As to the values at those indexes whose function values are not specifically defined, we can adopt one of three ways: 1) set them to NaN, 2) set them to 0, or more preferably 3), set them to a more meaningful value. In the case of sma, the more meaningful value in method 3) can be the average of the available values up to the index under calculation. For instance, when calculating a 10-bar sma, at index 3, the sma can be (v[1] + v[2] + v[3])/3.

**Comment by milktrader** [comment]
We now have `Nullable{Float64}` so each method can have a kwarg something like `consume=true` where the idea is by default, dates consumed to computation are removed. Setting this to `false` will keep the original `Array{Date}`  in place and put `Nullable{Float64}` in the values slot(s).

I'm closing this for now and opening a new issue on bike shedding the name for this kwarg.

**Comment by milktrader** [comment]
https://github.com/JuliaQuant/MarketTechnicals.jl/issues/47
