### ISSUE TITLE
Migrate doc generator to Documentor.jl?

### ISSUE THREAD

**Issue by iblis17** [JuliaQuant/MarketTechnicals.jl#58]
FYI: https://juliadocs.github.io/Documenter.jl/stable/

I can work on this migration.

**Comment by milktrader** [comment]
Okay, keep it up then. I'm going to start merging these.

**Comment by milktrader** [comment]
It appears the migration to `.md` from `.rst` isn't look all that good.

**Comment by iblis17** [comment]
closed via #69
