### ISSUE TITLE
New Documenter.jl migration 

### ISSUE THREAD

**Issue by milktrader** [JuliaQuant/MarketTechnicals.jl#63]
First, the readthedocs pages are not rendering ...

![screen shot 2017-03-16 at 9 47 26 am](https://cloud.githubusercontent.com/assets/324836/23999198/f514de24-0a2d-11e7-82f8-4b095983042d.png)

And in repl, the help docs are not rendering either ... 

![screen shot 2017-03-16 at 9 51 38 am](https://cloud.githubusercontent.com/assets/324836/23999256/2d83f0e2-0a2e-11e7-9316-f84f5ae7c3aa.png)

**Comment by iblis17** [comment]
The doc generated by Documenter.jl usually hosted on GH page.
Please see this also:
https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#Hosting-Documentation-1

**Comment by iblis17** [comment]
And.... the LaTex syntax is just a raw string under REPL

**Comment by iblis17** [comment]
@milktrader need help?

**Comment by milktrader** [comment]
Yes I have been swamped lately

**Comment by iblis17** [comment]
> What will happen with the read the docs? It goes away in favor of GH pages?

looks like Julia also migrated from RTD to GH pages: https://github.com/JuliaLang/julia/tree/gh-pages

> The LaTeX will render in some IDEs no?

Not sure, i'm not using any IDE....
Documenter.jl can render it via MathJax. (https://juliadocs.github.io/Documenter.jl/stable/man/latex.html)

**Comment by iblis17** [comment]
Here is a my working dir: http://140.113.73.135:8900/

**Comment by iblis17** [comment]
If you really want to deploy doc on RTD, I can investigate on it.

**Comment by milktrader** [comment]
This would be a good package to migrate to GH pages.

**Comment by iblis17** [comment]
👌

**Comment by iblis17** [comment]
closed via #69
