### ISSUE TITLE
Adaptive Moving Average

### ISSUE THREAD

**Issue by iblis17** [JuliaQuant/MarketTechnicals.jl#64]
Just discovered this:
https://www.tradingtechnologies.com/help/x-study/technical-indicator-definitions/adaptive-moving-average-ama/

(added to my TODO

**Comment by milktrader** [comment]
@iblis17 do you have time to work on this package? I'm tapped out for a few months at least and I can give you privileges to tidy things up here if you have time and urge do to so.

**Comment by iblis17** [comment]
@milktrader I can take it :) I have an easy schedule this weekend.

**Comment by milktrader** [comment]
You've been invited. Once you accept you should have push privileges to the MarketTechnicals repo.
